### ISSUE TITLE
public contributed project: https://ternow.ai/automatic-covid-19-diagnosis

### ISSUE THREAD

**Issue by arasharchor** [ieee8023/covid-chestxray-dataset#103]
Hi @ieee8023 
This is not an issue
I saw this and I thought it would be of interest for you
https://ternow.ai/automatic-covid-19-diagnosis/

**Comment by ieee8023** [comment]
Thank you. Do you have any chest X-rays that you can contribute from that project?

**Comment by arasharchor** [comment]
@ieee8023  not really. I just saw that I thought it would be of interest to join the forces
