### ISSUE TITLE
How to download nifty images from radiopaedia

### ISSUE THREAD

**Issue by JunMa11** [ieee8023/covid-chestxray-dataset#108]
Dear @ieee8023 ,

Thanks for the great repo.

Could you show me how to download nifty images from radiopaedia as you did [here](https://academictorrents.com/details/136ffddd0959108becb2b3a86630bec049fcb0ff)?

Kindest regards,
Jun

**Comment by ieee8023** [comment]
The script is here: https://github.com/ieee8023/covid-chestxray-dataset/blob/master/scripts/radiopedia.ipynb

**Comment by JunMa11** [comment]
Thank you so much!
