### ISSUE TITLE
Two Lateral images misannotated view = 'PA' in metadata

### ISSUE THREAD

**Issue by mwestt** [ieee8023/covid-chestxray-dataset#109]
I just wanted to highlight that two images have the wrong view metadata, both being labelled as 'PA' despite being lateral. I've updated them and happy to submit a PR if desired.

`pneumocystis-jiroveci-pneumonia-4-L.png`

<img src="https://user-images.githubusercontent.com/35194086/81369360-36755080-90c0-11ea-8867-bcd7bea1fd09.JPG" width="300">

`covid-19-infection-exclusive-gastrointestinal-symptoms-l.png`

<img src="https://user-images.githubusercontent.com/35194086/81369373-3d03c800-90c0-11ea-82c0-6722c7530864.JPG" width="350">

**Comment by ieee8023** [comment]
Yes please submit a pull request!

**Comment by ieee8023** [comment]
Fixed in #110 and 10f0e4e
