### ISSUE TITLE
A limit on length of filenames for the images

### ISSUE THREAD

**Issue by princyok** [ieee8023/covid-chestxray-dataset#114]
Some of the filenames are very long (I noticed one is 85 characters long). Windows has a limit on the length of file paths and causes some headache if exceeded.

Instead of having a lot descriptive information in the filename, maybe a new field for `description` can be included in the metadata, or just use the already existing `clinical_notes` field.

**Comment by ieee8023** [comment]
The filenames act as unique IDs when trying to spot duplicates from sites so we shouldn't change them as there is no issue on Mac and Linux.

Maybe you can zip up the image folder and then use a library to read from the zip file? I would take that as a pull request to torchxrayvision if you did write it. For example https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.read
