### ISSUE TITLE
Article about pneumonia hierarchy

### ISSUE THREAD

**Issue by lucasxteixeira** [ieee8023/covid-chestxray-dataset#115]
Even though the identification of Bacterial vs Viral vs COVID-19 Pneumonia not being much clinically relevant our research group tried to explore it considering a machine learning point of view.
We explored a series of feature extractions, fusion and resampling methods and achieved a good result.
Our publication have just been accepted on Computer Methods and Programs in Biomedicine Journal (https://www.sciencedirect.com/science/article/pii/S0169260720309664).
Anyway, I just want to say thank you for putting this repo together.

**Comment by ieee8023** [comment]
Thanks for sharing!

By quickly reading over the methods section it is not clear to me how you are using the hierarchy. 

I'll close this issue now as it is not an issue that needs to be resolved.
