### ISSUE TITLE
How am I allowed to use these resources?

### ISSUE THREAD

**Issue by platisd** [ieee8023/covid-chestxray-dataset#130]
Hi,
You've got a great dataset here and several other resources (e.g. Python scripts) however I am not sure how to use them. This is because after looking around, I could not find any licensing information.
Considering this you obtain all copyright to this work and therefore it'd be illegal for me to use it in any meaningful way other than just browsing through it.
Furthermore, this may itself not be right since, from what I understand, you are using resources that are distributed under particular CC licenses.

Could you please add a license or if that is done already, clarify which one it is? Thanks!

**Comment by ieee8023** [comment]
Thanks for pointing that out. I just added a clear statement in the README:

> Each image has license specified in the metadata.csv file. Including Apache 2.0, CC BY-NC-SA 4.0, CC BY 4.0.
> The metadata.csv, scripts, and other documents are released under a CC BY-NC-SA 4.0 license. Companies are free to perform research. Beyond that contact us.

**Comment by platisd** [comment]
Sounds good, thanks!
