### ISSUE TITLE
Offset values are negative for some cases?

### ISSUE THREAD

**Issue by SeanKski** [ieee8023/covid-chestxray-dataset#136]
These should be positive correct? Or is there some meaning to a patient having a negative offset?

**Comment by ieee8023** [comment]
The offset is time since admission or symptoms. So negative means from before this. Possibly they were at the hospital for something else where they had an x-ray and then caught the virus.

**Comment by SeanKski** [comment]
> Possibly they were at the hospital for something else where they had an x-ray and then caught the virus.

Thank you for your response! I thought the same thing, however, there are patients with only one image that have a negative offset but still a finding of COVID-19 (e.g. patientid 232). 

Does this mean that the patient was later found to have COVID-19, but this X-ray is just a scan of their lungs pre-virus?

**Comment by ieee8023** [comment]
I see patientid 232 is like that. I'll look into it more.

**Comment by ieee8023** [comment]
There was an update to the Hanover data that changed a bunch of offsets. @bganglia is working on it now to update the offsets for those images.

**Comment by SeanKski** [comment]
Great! Thank you :)
