### ISSUE TITLE
v7labs lung segmentations

### ISSUE THREAD

**Issue by ieee8023** [ieee8023/covid-chestxray-dataset#138]
This looks really nice. We should investigate it more and link to it or add it if everything checks out. The license is CC-BY.

https://github.com/v7labs/covid-19-xray-dataset

**Comment by simedw** [comment]
Hi @ieee8023 

Thanks for the kind words. We recently included png masks directly into the repo, you can find them at https://github.com/v7labs/covid-19-xray-dataset/tree/master/annotations/all-images-semantic-masks .

If you have any questions or if there is anything we can do to help with the integration of our annotations into your dataset please let me know!
