### ISSUE TITLE
How can we generate labels for these images?

### ISSUE THREAD

**Issue by ayaanzhaque** [ieee8023/covid-chestxray-dataset#139]
While code file allows us to get the labels for the images? For those that have labels of course.

**Comment by ieee8023** [comment]
In the readme file there is a link to the metadata.csv file which has information about each image. There is a link to a dataloader from torchxrayvison that will read the metadata file and provide a structured interface.

You may want to look at this code as an example of tasks to predict: https://github.com/mlmed/torchxrayvision/tree/master/scripts/covid-baselines
