### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [ieee8023/covid-chestxray-dataset#140]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/ACQJYE
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ieee8023** [comment]
Thanks for spreading the word about this dataset. 

> Would you be willing to help with the maintenance of your dataset in Dataverse

I don't see how Dataverse is better than this repository. Can you explain more? I think being indexed there will allow people to follow links to get to this repository. Managing the dataset is super easy on GitHub.
