### ISSUE TITLE
Reason for some removed images

### ISSUE THREAD

**Issue by gondimjoaom** [ieee8023/covid-chestxray-dataset#149]
Hi! First, thanks for the dataset preparation. I had cloned this repo back in April an just downloaded more images yesterday and realized that some images (about 75) from April's "image" folder where removed. I'm note complaining, but I would like to know if there ir a general reason for such.

**Comment by ieee8023** [comment]
We are constantly doing quality control on the data. Those images were likely of bad quality. We also add images marked as "todo" in the finding column of the metadata file (so they are not "added" to the dataset yet) and then we review them and may remove them.

**Comment by gondimjoaom** [comment]
Thanks for such fast response!!
