### ISSUE TITLE
(perhaps) missing data

### ISSUE THREAD

**Issue by ekdnam** [ieee8023/covid-chestxray-dataset#152]
I am trying to create a custom data-loader for this dataset. While looping through the metadata.csv file, I found that the following zip files cannot be found in the 'images' directory. 

<img width="358" alt="missing-files-covidchexray" src="https://user-images.githubusercontent.com/40426312/89187774-59c67380-d5bb-11ea-8584-7efffcc2bc30.png">

Where can these files be found?

**Comment by ieee8023** [comment]
Those are CT volumes You should also filter for modality. You only want "X-ray". Also there is a "folder" column too that you can filter for "images".

**Comment by ekdnam** [comment]
Okay thanks a lot
