### ISSUE TITLE
Covid dataset label help

### ISSUE THREAD

**Issue by aniketmaurya** [ieee8023/covid-chestxray-dataset#167]
In Covid dataloader, `d_covid19[idx]['lab']` is an array of length 25.
Is covid label at location 3, i.e. `d_covid19[idx]['lab'][3]`?

**Comment by ieee8023** [comment]
The lab array is aligned with dataset.pathologies which varies between datasets.

Take a look at: https://github.com/mlmed/torchxrayvision/blob/master/scripts/xray_datasets.ipynb
At the bottom xrv.datasets.relabel_dataset is used to align the pathologies and labels across all the datasets.

**Comment by aniketmaurya** [comment]
so after doing this my lab array will only contain label for covid-19 positive or negative, where positive means 1?
```
pathalogies = ['COVID-19']
relabel_dataset(pathalogies, d_covid19)
```

**Comment by ieee8023** [comment]
Yes exactly.

I urge you to read over the other tasks discussed in this paper which may be more relevant to helping physicians manage patients. Detecting COVID-19 is not that useful. https://arxiv.org/abs/2006.11988

**Comment by aniketmaurya** [comment]
sure! thanks a lot for the quick response
