### ISSUE TITLE
"good", "bad" patient states in the UMAP (Figure 3 in the paper)

### ISSUE THREAD

**Issue by Mda233** [ieee8023/covid-chestxray-dataset#199]
Hi,

Firstly, I want to appreciate your excellent work and the dataset release.

I was trying to reproduce the UMAP as drawn in Figure 3 by following "A good state is defined as non-intubated, not in the ICU, or the last state before discharge. A bad state is defined as intubated, in the ICU, or any state which is the last in the series and the patient is determined to have died." However, I have too many "bad" state dots shown in my figure.

Could you please tell me the exact rules you select for the "good"/"bad" states, or release the script for drawing that UMAP? 

It would be a great help for my work.I am looking forward to hearing from you.

Thank you!

**Comment by ieee8023** [comment]
Thanks for reaching out. I thought it was online but it isn't. I found a copy and I'll clean it up and put it online in the next day or so.

**Comment by ieee8023** [comment]
It was easier than I expected! Here it is: https://github.com/mlmed/torchxrayvision/blob/master/scripts/xray_trajectory.ipynb

**Comment by Mda233** [comment]
Thank you so much!
