### ISSUE TITLE
Sharing my data

### ISSUE THREAD

**Issue by AleGiovanardi** [ieee8023/covid-chestxray-dataset#21]
Hi I am doing some research on this topic applying CNN with deep learning to create an automated comupter vision based scanner to detect covid posivites and negatives scans.

Here you can find my dataset, I am currently building a CT scans dataset to try and train a model for ct scan other than rx scans. https://github.com/AleGiovanardi/covidhelper/tree/master/dataset/covidct

I also have a source of new rx and cts directly from italian hospital so i will update it periodically. You are welcome to take any of the data in my repo which are missing from here.

You can find also a code which train a model, save it and let you use it to test detection of scans, which is based on Adrian Rosebrock tutorial on pyimagesearch. I am constantyl working to enhance the performance and the accuracy of it.

Also thanks for your great job, this inspired me a lot!

**Comment by ieee8023** [comment]
I believe you are using the same images from this repo? It would help me if you could identify the ones that are not present in this dataset and have the source that they came from so I can correctly add the metadata.

The normal cases you are using are pediatric xrays so it your model just has to predict age and not the presence of the infection.

**Comment by AleGiovanardi** [comment]
I added more than 250 cases to normal dataset and more to Covid positives. Also I built a CT scans dataset which counts a lot of positives confirmed cases.
I trained some models on CT instead of RX and I can affirm the pathway is much more reliable. I also debugged my model with grad-CAM and found that the model is looking quite fine at the right regions in the image while learning. 
Again you can check the news on my repo. 

Kind regards.

**Comment by RazaGR** [comment]
@AleGiovanardi have you seen ieee8023 comment tp Adrian Rosebrock here https://github.com/ieee8023/covid-chestxray-dataset/issues/20#issuecomment-600154029

>I find the main issue with your work is the evaluation. You simply cannot claim the model has such high performance. You are only using train and valid sets and no external test set. You should also perform some sort of cross-validation to assess how well the model generalizes.

Have you comply with above?

**Comment by AleGiovanardi** [comment]
I test the models against unknown images. Images used for testing ARE NOT used for training the model.
