### ISSUE TITLE
Offset field

### ISSUE THREAD

**Issue by caginpolat** [ieee8023/covid-chestxray-dataset#22]
What is the meaning of the offset field?

**Comment by ieee8023** [comment]
Time when symptoms started

**Comment by bganglia** [comment]
@caginpolat @ieee8023 In the entries I was looking at, it looked like the offset was the number of days after hospitalization the radiograph was taken. 

I think it would be a good idea to add a "data dictionary" for the metadata. I have one on my branch right now and can make a PR.

**Comment by ieee8023** [comment]
@bganglia this sounds like a good idea. At first the field was just some way of establishing a temporal order so it was the first day in the hospital or the first day they reported symptoms. I was thinking the difference between the times was more important than the exact start time.

**Comment by bganglia** [comment]
@ieee8023 I am making the PR right now. I would appreciate it if you could take a look and let me know if you think there are any other fields that need explanation. I was not sure about the "date" field myself

**Comment by ieee8023** [comment]
Ok I merged it and added/changed some text. I'm happy to change my mind on any assumptions there if you feel differently.

Thanks for your help!
