### ISSUE TITLE
where are the computed tomography (CT) images?

### ISSUE THREAD

**Issue by tianmaliuixing** [ieee8023/covid-chestxray-dataset#35]
I can't find the CT images.

**Comment by ieee8023** [comment]
There are some slices there but not many. I am still waiting for people to make CTs public.

**Comment by tianmaliuixing** [comment]
> There are some slices there but not many. I am still waiting for people to make CTs public.

Thank you for your reply. But I can't find any CT in images folder. Could you point it out clearly？
Thanks,

**Comment by bganglia** [comment]
@tianmaliuixing if you really need CT images, you can select the rows in metadata.csv where modality = CT and then use the filename column. There are not as many, though.

**Comment by AleGiovanardi** [comment]
You can check my repo for a CT scans public dataset.
https://github.com/AleGiovanardi/covidhelper and you are welcome to contribute also!

**Comment by MicPie** [comment]
This is great, do you know any other public sources for CT scans of COVID-19 cases?
