### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by yeldarby** [ieee8023/covid-chestxray-dataset#4]
Thank you so much for curating this dataset! Hopefully we can all work together to scale up detection of coronaviruses via radiography.

Could you please add a `LICENSE` file for the images and annotations in this repository? We'd like to be able to use and remix them but need clarification of the terms under which they're allowed to be used and shared.

**Comment by ieee8023** [comment]
So an overall license may be difficult because each image can have its own copyright. Many are CC-SA. I will add a column to the metadata.csv file. At some point there can be a script to extract to generate a version of the dataset which only includes images with a specific open license like CC-SA.
