### ISSUE TITLE
What is the offset ?

### ISSUE THREAD

**Issue by Abubakar26** [ieee8023/covid-chestxray-dataset#45]
Can anybody explain what is the purpose of offset values I am having issues to understand what it is

**Comment by bganglia** [comment]
@Abubakar26 You can find metadata explanations [here](https://github.com/ieee8023/covid-chestxray-dataset/blob/master/CONTRIBUTING.md). The offset is the number of days after hospitalization/start of symptoms for each image.

**Comment by Abubakar26** [comment]
@bganglia  Thanks brother
