### ISSUE TITLE
 5 South Korea papers still not included in metadata

### ISSUE THREAD

**Issue by ncovgt2020** [ieee8023/covid-chestxray-dataset#59]
- Published online March 5, 2020. https://doi.org/10.3348/kjr.2020.0146 
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-505.pdf

- Published online March 20, 2020. https://doi.org/10.3348/kjr.2020.0195
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-e45.pdf

- Published online March 20, 2020. https://doi.org/10.3348/kjr.2020.0180
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-e43.pdf

- Published online March 13, 2020. https://doi.org/10.3348/kjr.2020.0181
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-e42.pdf

- Published online March 13, 2020. https://doi.org/10.3348/kjr.2020.0157
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-e39.pdf

- Published online February 11, 2020. https://doi.org/10.3348/kjr.2020.0078
https://kjronline.org/Synapse/Data/PDFData/0068KJR/kjr-21-365.pdf

Found using advanced search of the Korean Journal of Radiology kjronline[.]org searching the term "covid-19" filtering for years 2018 - 2020

**Comment by bganglia** [comment]
@ncovgt2020 Thank you so much.

@ieee8023 I can work on adding these

**Comment by ieee8023** [comment]
@bganglia Ok, I won't commit anything until you push something.

**Comment by bganglia** [comment]
@ieee8023 Actually it looks like these are all CTs.

**Comment by ncovgt2020** [comment]
Hi guys,

**Comment by ncovgt2020** [comment]
@ieee8023 is this project interested in x-ray images only? I am actively looking for papers still missing. Should I not inform of papers when those contain CT images only? Thanks.

**Comment by ieee8023** [comment]
In my work I'm only using chest X-ray images or CT volumes. The slices are not as useful for building tools IMO. But if someone is using them and extracts them I would merge the pull requests.
