### ISSUE TITLE
More Clinical note about other patients with SARS or ARDS or pneumonia

### ISSUE THREAD

**Issue by JiayuanDing100** [ieee8023/covid-chestxray-dataset#62]
Anyone knows where we could find more clinical note about SARS or ARDS or pneumonia patients? I want to do some research on covid-19 classification based clinical note.
In current metadata, there are 92 covid-19 instances compared to 14 none covid-19 instances.
Really appreciate it if anyone could provide more useful info

**Comment by ieee8023** [comment]
Check out https://radiopaedia.org/ for other cases. If you can, add the cases you find to this database as well!
