### ISSUE TITLE
Papers containing CT and Xray that are not in metadata.csv

### ISSUE THREAD

**Issue by ncovgt2020** [ieee8023/covid-chestxray-dataset#63]
- Published Online:Feb 13 2020
https://doi.org/10.1148/radiol.2020200370

- Published Online:Feb 20 2020
https://doi.org/10.1148/radiol.2020200463

- Published Online:Feb 12 2020
https://doi.org/10.1148/ryct.2020200026

- Published Online:Feb 13 2020
https://doi.org/10.1148/ryct.2020200025

- Published Online:Feb 14 2020
https://doi.org/10.1148/ryct.2020200031

- Published Online:Feb 14 2020
https://doi.org/10.1148/ryct.2020200033

- Published Online:Feb 4 2020
https://doi.org/10.1148/radiol.2020200230

- Published Online:Feb 6 2020
https://doi.org/10.1148/radiol.2020200274

- Published Online:Feb 12 2020
https://doi.org/10.1148/radiol.2020200343

Found in the description of the following corona virus analysis video.
https://www.youtube[.]com/watch?v=oOlJs7bJ0ho

**Comment by bganglia** [comment]
@ieee8023 I can work on this

**Comment by bganglia** [comment]
@ncovgt2020 Thanks! I will be making a PR with some of these papers shortly
