### ISSUE TITLE
Does the folder `image` only consist of Chest X-Rays of patients diagnosed with COVID-19?

### ISSUE THREAD

**Issue by aparnapanicker** [ieee8023/covid-chestxray-dataset#68]
Hi @ieee8023 ,  

May I know whether all images present in the folder `images` contains only the X-Ray image of patients  diagnosed with `COVID-19` ?  Or is it the mix of Chest X-Rays of patients diagnosed with COVID-19, MERS, SARS, and ARDS. Also , If the image  folder have mix of all the chest X-Rays of patients diagnosed with COVID-19, MERS, SARS, and ARDS, May I know how to fetch only the image for COVID-19. 

With Regards,
Aparna

**Comment by ieee8023** [comment]
The metadata file contains the findings information you are looking for.

**Comment by aparnapanicker** [comment]
Hi @ieee8023 , 

May I know whether there are any ethical issues associated with using this data set as part of my project?

**Comment by ieee8023** [comment]
The data is composed from public sources. Check with your ethics board.
