### ISSUE TITLE
South Korea papers still not in metadata.csv

### ISSUE THREAD

**Issue by ncovgt2020** [ieee8023/covid-chestxray-dataset#70]
- Lei P, Mao J, Huang Z, Liu G, Wang P, Song W.   Key Considerations for Radiologists When Diagnosing the Novel Coronavirus Disease (COVID-19).   Korean J Radiol. 2020 Jan;21:e44.   https://doi.org/10.3348/kjr.2020.0190

- Yoon SH, Lee KH, Kim JY, Lee YK, Ko H, Kim KH, Park CM, Kim YH.   Chest Radiographic and CT Findings of the 2019 Novel Coronavirus Disease (COVID-19): Analysis of Nine Patients Treated in Korea.   Korean J Radiol. 2020 Apr;21(4):494-500.   https://doi.org/10.3348/kjr.2020.0132

- Wei J, Xu H, Xiong J, Shen Q, Fan B, Ye C, Dong W, Hu F.   2019 Novel Coronavirus (COVID-19) Pneumonia: Serial Computed Tomography Findings.   Korean J Radiol. 2020 Apr;21(4):501-504.   https://doi.org/10.3348/kjr.2020.0112

These are also not included in my previous issue #59 on South Korean papers. Obtained with help from https://cafe.naver.com/mskmri/134

**Comment by bganglia** [comment]
@ncovgt2020 Thanks!

**Comment by bganglia** [comment]
It looks like the radiographs from these papers have already been added, so I will close this issue.

**Comment by juanmed** [comment]
Hi,

When I added these papers, I checked twice on the `metadata.csv` and my previous issues. At that moment, they were not included anywhere. How do you know they were already added?  It is just that I am looking for more papers, and if I am overseeing something I would like to know. Thanks.

**Comment by ncovgt2020** [comment]
Hi,

When I included these papers, I checked in `metadata.csv` file and my previous issues. They were not included anywhere. How do you know these have been already included? Since I am actively looking for more papers, I am probably overseeing something, and I would like to know what if that is the case. Thanks.

**Comment by bganglia** [comment]
@ncovgt2020 I have been checking by seeing if the DOI is in the file. Also, right now we are mainly focusing on adding X-rays, so we may not add papers with just CTs.

Thank you for your work. The radiographs just sitting in papers are the hardest to find

**Comment by ncovgt2020** [comment]
Thank you for your answer. I will not be reporting papers with CT only in future issues. Regards!
