### ISSUE TITLE
More Radiopaedia images 4/5/2020

### ISSUE THREAD

**Issue by bganglia** [ieee8023/covid-chestxray-dataset#73]
I thought that it might be more convenient to create a single issue, as @ncovgt2020 has been doing. 

- [x] https://radiopaedia.org/cases/covid-19-pneumonia-8?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-20?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-22?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-34?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-38?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-35?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-41?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-44?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-58?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-mild?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-67?lang=us
- [x] https://radiopaedia.org/cases/covid-19-pneumonia-bilateral
- [x] https://radiopaedia.org/cases/early-stage-covid-19-pneumonia-1?lang=us

**Comment by ieee8023** [comment]
Oh wow! I didn't see that I missed those! This one is already there but with a different spelling:

https://radiopaedia.org/cases/post-intubuation-pneumomediastium-and-pneumothorax-background-covid-19-pneumonia

It seems that it is an alias for patientid 142.

Also, I would skip the https://radiopaedia.org/cases/covid-19-pneumonia-paediatric one because it is a child. We should set a lower age limit to 18.

**Comment by bganglia** [comment]
@ieee8023 Thanks! I will update the list. Right now I am about a third of the way through adding these and my target is to finish by tonight or tomorrow morning. The highest ID will probably be 185ish, in case you are adding anything else at the same time.

I will stay on the lookout for other sites like Eurorad.

**Comment by bganglia** [comment]
I didn't end up getting through all of these, so I will have to make another PR later today or tomorrow.

**Comment by hitesh-hk** [comment]
Have you added those images @ieee8023  which were uploaded by @bganglia ?

**Comment by bganglia** [comment]
@hitesh-hk I am preparing the PR for those images right now. There was an encoding issue with the file, so I am fixing that right now. Then I will make the PR

**Comment by hitesh-hk** [comment]
Sure I will wait for sometime @bganglia. Please comment here once you are done with PR. Thanks for the quick reply.

**Comment by bganglia** [comment]
@hitesh-hk These images have now all been merged.

**Comment by hitesh-hk** [comment]
Thanks @bganglia
