### ISSUE TITLE
Visually understand metadata

### ISSUE THREAD

**Issue by ncovgt2020** [ieee8023/covid-chestxray-dataset#82]
Is a visualization of the metadata useful to this repository?  I made [this](https://github.com/ncovgt2020/covid_chestxray_dataset/blob/master/scripts/metadata_visualization.ipynb). Can make a pull request if you find it useful.

**Comment by ieee8023** [comment]
Looks great! Please make a pull request! You can add your name at the top of the notebook as well!

**Comment by ncovgt2020** [comment]
Made pull request #87.
