### ISSUE TITLE
 What machine is used to scan those images?

### ISSUE THREAD

**Issue by rodrigocardoso92** [ieee8023/covid-chestxray-dataset#91]
Hello contributors, I think that the information about the machines used for digitalize those images is important, can u get these information, plz?

**Comment by ieee8023** [comment]
*you and *please. We are not texting each other.

This information is rare to find for chest X-rays. Also, it is not clear it matters. Acquisition parameters would make more sense and I don't even see this info in the DICOM headers to X-rays. It is more important for CTs. 
Do you have any references saying that chest X-ray algorithms perform differently given the machine/acquisition parameters?
