### ISSUE TITLE
Error!! UTF-8 encoded Saving disable

### ISSUE THREAD

**Issue by stu93303148** [ieee8023/covid-chestxray-dataset#94]
How to fix it?

<img width="1187" alt="螢幕快照 2020-04-22 上午12 23 11" src="https://user-images.githubusercontent.com/1113604/79888583-7b965300-842f-11ea-8a51-ee83c0748a86.png">

**Comment by ieee8023** [comment]
I don't think you can view those files in jupyter notebook.
